name: Authentication Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.5'
        extensions: mbstring, xml, ctype, iconv, mysql

    - name: Cache Composer Packages
      uses: actions/cache@v4
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-git

    - name: Install Dependencies
      run: composer install --no-progress --prefer-dist

    - name: Copy .env file
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Configure environment for SQLite
      run: |
        sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/' .env
        sed -i 's/^DB_DATABASE=laravel/#DB_DATABASE=laravel/' .env

    - name: Remove current tests and symlink to DevDojo Auth
      run: |
        rm -rf tests
        ln -s vendor/devdojo/auth/tests tests

    - name: Create sqlite file
      run: touch database/database.sqlite

    - name: Run the migrations
      run: php artisan migrate --force

    - name: Run the Auth Migrations
      run: php artisan migrate --path=vendor/devdojo/auth/database/migrations --force

    - name: Install PestPHP
      run: composer require pestphp/pest --dev --with-all-dependencies

    - name: Run Tests
      run: ./vendor/bin/pest
